---
# This workflow will build an Xcode project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
      - name: Build
        run: |
          xcodebuild clean build \
            -project ManusPsiqueia.xcodeproj \
            -scheme ManusPsiqueia \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
            -configuration Debug \
          CODE_SIGNING_ALLOWED=NO

      - name: Run tests
        run: |
          xcodebuild test \
            -project ManusPsiqueia.xcodeproj \
            -scheme ManusPsiqueia \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
            -configuration Debug \
          CODE_SIGNING_ALLOWED=NO
