name: ✨ Feature Request
description: Suggest a new feature or enhancement for ManusPsiqueia
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        
        Thank you for suggesting a new feature! Your ideas help make ManusPsiqueia better for everyone.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with ManusPsiqueia's mission of mental health care
          required: true
        - label: I have considered the impact on both psychologists and patients
          required: true

  - type: dropdown
    id: priority
    attributes:
      label: Feature Priority
      description: How important is this feature?
      options:
        - Critical (Essential for core functionality)
        - High (Significantly improves user experience)
        - Medium (Nice to have, moderate impact)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the app would this feature affect?
      options:
        - Authentication & Security
        - Payment & Billing
        - Dashboard & Analytics
        - Communication & Chat
        - AI & Automation
        - User Interface & UX
        - Notifications
        - Reporting & Insights
        - Integration & API
        - Accessibility
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Primary Beneficiary
      description: Who would primarily benefit from this feature?
      options:
        - Psychologists
        - Patients
        - Both equally
        - Platform administrators
        - Third-party integrators
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the current pain point or limitation that this feature would address.
        
        Example: "Currently, psychologists have no way to track patient progress over time, making it difficult to adjust treatment plans effectively."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed feature in detail
      placeholder: |
        Provide a detailed description of the feature you'd like to see implemented.
        
        Include:
        - How it would work
        - User interactions
        - Expected outcomes
        - Integration points
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: User Stories
      description: Describe how different users would interact with this feature
      placeholder: |
        Write user stories in the format: "As a [user type], I want [goal] so that [benefit]"
        
        Examples:
        - As a psychologist, I want to view patient progress charts so that I can adjust treatment plans
        - As a patient, I want to receive session reminders so that I don't miss appointments
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        List specific, measurable criteria that define when this feature is done.
        
        Example:
        - [ ] Psychologists can create custom progress metrics
        - [ ] Charts display data from the last 6 months
        - [ ] Data exports to PDF format
        - [ ] Mobile responsive design
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have visual ideas, share them here
      placeholder: |
        Attach mockups, wireframes, or sketches if available.
        You can also describe the visual layout in text.

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (1-2 days)
        - Medium (1-2 weeks)
        - Complex (1-2 months)
        - Very Complex (3+ months)
        - Not sure
    validations:
      required: true

  - type: checkboxes
    id: considerations
    attributes:
      label: Technical Considerations
      description: What technical aspects should be considered?
      options:
        - label: Requires backend API changes
        - label: Needs database schema updates
        - label: Involves third-party integrations
        - label: Requires new UI components
        - label: Impacts performance
        - label: Affects security/privacy
        - label: Needs offline capability
        - label: Requires push notifications

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        Describe any alternative solutions or workarounds you've considered.
        Why do you prefer your proposed solution?

  - type: textarea
    id: business_impact
    attributes:
      label: Business Impact
      description: How would this feature impact the business?
      placeholder: |
        Consider:
        - User retention and engagement
        - Revenue potential
        - Competitive advantage
        - Market differentiation
        - User acquisition

  - type: checkboxes
    id: related_features
    attributes:
      label: Related Features
      description: Does this feature relate to or depend on other features?
      options:
        - label: Depends on existing features
        - label: Enables future features
        - label: Replaces existing functionality
        - label: Integrates with external services
        - label: Requires new permissions

  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics
      description: How would you measure the success of this feature?
      placeholder: |
        Define metrics that would indicate this feature is successful:
        
        Examples:
        - 80% of psychologists use the progress tracking feature within 30 days
        - Patient session attendance increases by 15%
        - User satisfaction score improves by 0.5 points
        - Feature adoption rate reaches 60% within 3 months

  - type: dropdown
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature implemented?
      options:
        - ASAP (Critical need)
        - Next release (1-2 months)
        - Within 6 months
        - Within 1 year
        - No specific timeline
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        Include:
        - Research or data supporting this feature
        - Examples from other apps
        - User feedback or requests
        - Regulatory requirements
        - Accessibility considerations

  - type: markdown
    attributes:
      value: |
        ## 🚀 Next Steps
        
        After submitting this feature request:
        1. Our product team will review and evaluate the proposal
        2. We'll assess technical feasibility and business impact
        3. The feature may be added to our product roadmap
        4. You'll receive updates on the status and timeline
        5. We may reach out for additional clarification
        
        Thank you for helping us build a better ManusPsiqueia! 🙏
